[package]
name = "winctrl"
version = "0.1.0"
edition = "2021"

[lib]
name = "winctrl"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_HiDpi",
    "Win32_Devices_Display",
    "Win32_Graphics_Gdi",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole",
]}